name: Prefetch Yahoo Data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 0-23 * * 1-5"  # every 30 minutes on weekdays

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run prefetch
        run: node scripts/prefetch-yahoo.js

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git diff --quiet --cached || git commit -m "chore(data): refresh Yahoo chart JSON"
          git push
